user_dir: "/home/azureuser"
app_port: 5000
service:
  workingdir: /home/azureuser/devopsproject/devopsproject
  execstart: /home/azureuser/devopsproject/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 devopsproject.wsgi:application

djangoservice:
  workingdir: /home/azureuser/devopsproject/devopsproject
  execstart: /home/azureuser/devopsproject/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 devopsproject.wsgi:application



app:
  env:
    SQLALCHEMY_DATABASE_URI: mysql://db_user:pass123@localhost:3308/django_Test
    SQLALCHEMY_TRACK_MODIFICATIONS: False
    SECRET_KEY: sfvgbrh212131

django:
  env:
    SECRET_KEY: 'sfvgbrh212131'
    DATABASE_URL: 'mysql://db_user:pass123@localhost:3308/django_Test'
