---
loadbalancer:
  hosts:
    lb01:
      ansible_host: lb01
webserver:
  hosts:
    app01:
      ansible_host: ProjDevops
    app02:
      ansible_host: ProjDevops
    db01:
      ansible_host: db01
      ansible_python_interpreter: /usr/bin/python3
  vars:
    ansible_python_interpreter: /usr/bin/python3
database:
  hosts:
    db01:
      ansible_host: db01
      ansible_python_interpreter: /usr/bin/python3
control:
  hosts:
    local-control:
      ansible_connection: local
