service:
  workingdir: /home/azureuser/flask-project/
  execstart: /home/azureuser/flask-project/fvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:{{app_port}} app.main:app
app_port: 8000

app:
  env:
    SQLALCHEMY_DATABASE_URI: mysql://db_user:pass123@localhost:3308/django_Test
    SQLALCHEMY_TRACK_MODIFICATIONS: False
    SECRET_KEY: sfvgbrh212131
