
user_dir: "/home/azureuser"


djangoservice:
  workingdir: /home/azureuser/myapp/myproject
  execstart: /home/azureuser/myapp/myvenv/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 myproject.wsgi:application

django:
  env:
    SECRET_KEY: 'sfvgbrh212131'
    DATABASE_URL: 'mysql://root:pass123456@localhost:3308/django_Test'

user_name: azureuser
app_port: 8000