- hosts: db01
  roles:
    - role: geerlingguy.mysql
      become: yes
  tasks:
    - name: change bind-address to '0.0.0.0'
      lineinfile:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: "^bind-address"
        line: "bind-address = 0.0.0.0"
        state: present
        backup: yes
      become: yes
      notify:
        - restart mysql
  tags:
    - mysql
  vars:
    mysql_databases:
      - name: django_Test
    mysql_users:
      - name: db_user
        password: pass123
        priv: 'demodb.*:ALL'
        host: '%'
    mysql_locales:
      - 'en_US.UTF-8'
